# Generated by Django 5.2.9 on 2025-12-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('category_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('category_master', models.CharField(blank=True, max_length=255, null=True)),
                ('source_system', models.CharField(blank=True, max_length=50, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'part_master',
                'ordering': ['part_number'],
                'managed': False,
            },
        ),
    ]
