# Generated by Django 5.2.9 on 2025-12-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partmaster',
            options={'ordering': ['part_number']},
        ),
    ]
